// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package test.test_pb3



object TestPb3Proto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cg50ZXN0X3BiMy5wcm90bxIEdGVzdBoVc2NhbGFwYi9zY2FsYXBiLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wL
  nByb3RvGh5nb29nbGUvcHJvdG9idWYvZHVyYXRpb24ucHJvdG8aHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVycy5wcm90byL0BAoHV
  GVzdFBCMxISCgRuYW1lGAEgASgJUgRuYW1lEjcKCGludFZhbHVlGAIgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWVSC
  GludFZhbHVlEjkKCWxvbmdWYWx1ZRgEIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQ2NFZhbHVlUglsb25nVmFsdWUSSgoRdW5za
  WduZWRMb25nVmFsdWUYBSABKAsyHC5nb29nbGUucHJvdG9idWYuVUludDY0VmFsdWVSEXVuc2lnbmVkTG9uZ1ZhbHVlEjsKCmZsb
  2F0VmFsdWUYBiABKAsyGy5nb29nbGUucHJvdG9idWYuRmxvYXRWYWx1ZVIKZmxvYXRWYWx1ZRI+Cgtkb3VibGVWYWx1ZRgHIAEoC
  zIcLmdvb2dsZS5wcm90b2J1Zi5Eb3VibGVWYWx1ZVILZG91YmxlVmFsdWUSOAoJYm9vbFZhbHVlGAggASgLMhouZ29vZ2xlLnByb
  3RvYnVmLkJvb2xWYWx1ZVIJYm9vbFZhbHVlEj4KC3N0cmluZ1ZhbHVlGAkgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1Zhb
  HVlUgtzdHJpbmdWYWx1ZRI7CgpieXRlc1ZhbHVlGAogASgLMhsuZ29vZ2xlLnByb3RvYnVmLkJ5dGVzVmFsdWVSCmJ5dGVzVmFsd
  WUSMAoFYmlydGgYCyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wUgViaXJ0aBIvCgVibGluaxgMIAEoCzIZLmdvb2dsZ
  S5wcm90b2J1Zi5EdXJhdGlvblIFYmxpbmtCBeI/AjABYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
  com.trueaccord.scalapb.Scalapb.getDescriptor(),
  com.google.protobuf.timestamp.TimestampProto.descriptor,
  com.google.protobuf.duration.DurationProto.descriptor,
  com.google.protobuf.wrappers.WrappersProto.descriptor
    ))
  }
}